version: "3"
services:
  nats:
    image: nats-streaming
    restart: always
    ports:
      - 4222
    command: "--dir /data"
    volumes:
      - ./nats-store:/data
  etcd:
    image: quay.io/coreos/etcd
    restart: always
    entrypoint: etcd
    command: >
      --data-dir=/data --name etcd1
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster-token
      --initial-cluster "etcd1=http://etcd:2380"
      --initial-advertise-peer-urls "http://etcd:2380"
      --initial-cluster-state new
      --auto-compaction-retention=1
      --quota-backend-bytes=102400000
    volumes:
      - ./etcd-data:/data
    ports:
      - 2379:2379
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=123456
#  clickhouse:
#    image: clickhouse/clickhouse-server
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#    ulimits:
#      nofile: "262144:262144"
#    volumes:
#      - ./clickhouse/data:/var/lib/clickhouse
#      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
#      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
  go2o:
    image: uhub.service.ucloud.cn/fze-registry/go2o
    depends_on:
      - "postgres"
      - "nats"
      - "etcd"
    restart: always
    ports:
      - "1427:1427"
      - "1428:1428"
    volumes:
      - ./go2o:/data
    environment:
      GO2O_NATS_ADDR: nats:4222
      GO2O_ETCD_ADDR: etcd:2379
      GO2O_SERVER_HOST:

